image: "sbtscala/scala-sbt:eclipse-temurin-focal-17.0.9_9_1.9.7_3.3.1"

variables:
  SBT_VERSION: "1.7.2"
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"

cache:
  key: "$CI_BUILD_REF_NAME" # contains either the branch or the tag, so it's caching per branch
  untracked: true
  paths:
    - "sbt-cache/.ivy.cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

stages:
  - build
  - test
  - package
  - doc
  - publish

build:
  stage: build
  tags:
    - OSCAR_CBLS_TEST
  script:
    - sbt clean compile

test:
  stage: test
  tags:
    - OSCAR_CBLS_TEST
  script:
    - sbt test

package:
  stage: package
  only:
    - main
  tags:
    - OSCAR_CBLS_TEST
  script:
    - sbt clean package packageDoc

doc:
  stage: doc
  only:
    - main
  tags:
    - OSCAR_CBLS_TEST
  script:
    - sbt doc

publish:
  stage: publish
  only:
    - main
  tags:
    - OSCAR_CBLS_TEST
  script:
    - sbt publish